spring:
  application:
    name: aicloud
  ai:
    openai:
      base-url: https://api.xiaoai.plus
      api-key: ${OPENAI_APIKEY}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
minio:
  endpoint: http://127.0.0.1:9000
  access-key: 6TXrcxNy0qrCVT4gAtLM
  secret-key: ma8VbphlwDqwWcWxmh2T3WGoCOTq4Xgs3jtxaCDf
  bucket: aicloud